name: Supply Chain

on:
  pull_request:
  push:
    branches: [main]
    tags:
      - "v*.*.*"
  schedule:
    - cron: "19 6 * * 2"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  security-governance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1
        with:
          version: 10.12.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm security:supply-chain
